name: 'Lost Pixel'
description: 'Lost Pixel Integration'
author: 'Chris Kalmar'
branding:
  icon: 'image'
  color: 'purple'
inputs:
  FINALIZE:
    description: 'Finalize run in a monorepo setup'
    required: false
  CACHE_KEY:
    description: 'Cache key for the build'
    required: false
  DOCKER_IMAGE:
    description: 'The Docker image to use for the action'
    required: false
runs:
  using: 'docker'
  image: "docker://${{ inputs.DOCKER_IMAGE || 'lostpixel/lost-pixel:v3.20.0' }}"
  # for branch testing
  # image: 'Dockerfile'
