name: 'Lost Pixel'
description: 'Lost Pixel Integration'
author: 'Chris Kalmar'
branding:
  icon: 'image'
  color: 'purple'
inputs:
  FINALIZE:
    description: 'Finalize run in a monorepo setup'
    required: false
runs:
  using: 'docker'
  image: 'docker://lostpixel/lost-pixel:v3.2.0'
