version: "3"

volumes:
  minio:


services:


  minio:
    image: minio/minio:RELEASE.2021-12-20T22-07-16Z
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio:/data"
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=m1n105ecr3t"
      - "MINIO_LISTEN_ON=:9000"
      - "MINIO_BROWSER=on"



