name: Lost Pixel feature request
description: Lost Pixel feature you would like to see in the next release
labels: 'kind/feature'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve Lost Pixel! 🙏 Please fill in the template to ensure we are aware of your use case!
  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Mode of the requested feature
      options:
        - Storybook
        - Ladle
        - Page screenshots
        - Other
  - type: textarea
    attributes:
      label: Feature description
      description: A clear description of what you would like to see released in next release of Lost Pixel
    validations:
      required: true
