on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm -g install jest

      - name: Test
        run: npm run test

      # - name: Build Demo Storybook
      #   run: |
      #     cd examples/storybook-demo
      #     npm ci
      #     npm run build-storybook

      # - name: Test Action Container 1
      #   uses: ./
      #   with:
      #     LOST_PIXEL_URL: ${{ secrets.LOST_PIXEL_URL_1 }}
      #     LOST_PIXEL_PROJECT_ID: ${{ secrets.LOST_PIXEL_PROJECT_ID_1 }}
      #     STORYBOOK_PATH: 'examples/storybook-demo/storybook-static'
      #     S3_END_POINT: 'fra1.digitaloceanspaces.com'
      #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      #     S3_BUCKET_NAME: 'lost-pixel'
      #     S3_BASE_URL: 'https://lost-pixel.fra1.digitaloceanspaces.com'

      # - name: Test Action Container 2
      #   uses: ./
      #   with:
      #     LOST_PIXEL_URL: ${{ secrets.LOST_PIXEL_URL_2 }}
      #     LOST_PIXEL_PROJECT_ID: ${{ secrets.LOST_PIXEL_PROJECT_ID_2 }}
      #     STORYBOOK_PATH: 'examples/storybook-demo/storybook-static'
      #     S3_END_POINT: 'fra1.digitaloceanspaces.com'
      #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      #     S3_BUCKET_NAME: 'lost-pixel'
      #     S3_BASE_URL: 'https://lost-pixel.fra1.digitaloceanspaces.com'

      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     LOST_PIXEL_URL: ${{ secrets.LOST_PIXEL_URL }}
      #     LOST_PIXEL_PROJECT_ID: 'l0s+p1xl'
      #     STORYBOOK_PATH: 'examples/storybook-demo/storybook-static'
      #     S3_END_POINT: 'fra1.digitaloceanspaces.com'
      #     S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      #     S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
      #     S3_BUCKET_NAME: 'lost-pixel'
      #     S3_BASE_URL: 'http://127.0.0.1:9000/lost-pixel'

