on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm -g install jest

      - name: Lint
        run: npm run lint

      - name: Build Example Storybook v6.4
        run: npm run build-example-storybook-v6.4

      - name: Build Example Storybook v6.5 with StoryStore v7
        run: npm run build-example-storybook-v6.5-storystore-v7

      - name: Build Example Pages
        run: npm run build-example-next-js-pages

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Run Example Next.js Pages
        run: npm run run-example-next-js-pages &

      - name: Run Ladle
        run: npm run run-example-ladle &

      - name: Test on examples
        run: npm run test-on-examples

      - name: Artifacts upload
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: shots
          path: examples/.lostpixel
